<?php
$View_SignMMk="no";
$View_BankName="";
$View_TName="";
$View_BankNo="";
$View_ContText_0="";
$View_ContText_1="";
$View_ContText_2="";
$View_ContText_3="";
$View_ContText_4="";
$View_ContText_5="";
$View_ContText_6="";
$View_ContText_7="";
$View_ContText_8="";
$View_ContText_9="";
$View_ContText_10="";
$View_ContText_11="";
$View_ContText_12="";
$View_ContText_13="";
$View_ContText_14="";
$View_ContText_15="";
$View_ContText_16="";
?>