name: Claude Code Integration

  on:
    push:
      branches: [ main, master ]
    pull_request:
      branches: [ main, master ]
    issues:
      types: [opened, edited]

  jobs:
    claude-assistance:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Claude Code Analysis
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "Claude Code integration ready"
          echo "API key configured: $(if [ -n "$ANTHROPIC_API_KEY" ]; then echo "YES"; else echo "NO"; fi)"
